#ddev-generated
# This file contains the configuration settings for Elasticsearch 8.
# For more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.19/settings.html

# https://www.elastic.co/guide/en/elasticsearch/reference/8.19/misc-cluster-settings.html#cluster-name
cluster.name: "docker-cluster"

# https://www.elastic.co/guide/en/elasticsearch/reference/8.19/important-settings.html#network.host
network.host: 0.0.0.0

# https://www.elastic.co/guide/en/elasticsearch/reference/8.19/modules-discovery-settings.html
discovery.type: single-node

# https://www.elastic.co/guide/en/elasticsearch/reference/8.19/setup-configuration-memory.html#bootstrap-memory_lock
bootstrap.memory_lock: true

# Disable security features
# https://www.elastic.co/guide/en/elasticsearch/reference/8.19/security-settings.html#general-security-settings
xpack.security.enabled: false
xpack.security.autoconfiguration.enabled: false
xpack.security.enrollment.enabled: false
