#ddev-generated
# This file contains the configuration settings for Elasticsearch 8.
# For more information, see https://www.elastic.co/guide/en/elasticsearch/reference/8.19/settings.html

# https://www.elastic.co/docs/deploy-manage/deploy/self-managed/important-settings-configuration#_cluster_name_setting
cluster.name: "docker-cluster"

# https://www.elastic.co/docs/deploy-manage/deploy/self-managed/important-settings-configuration#network.host
network.host: 0.0.0.0

# https://www.elastic.co/docs/reference/elasticsearch/configuration-reference/discovery-cluster-formation-settings
discovery.type: single-node

# https://www.elastic.co/docs/deploy-manage/deploy/self-managed/setup-configuration-memory#bootstrap-memory_lock
bootstrap.memory_lock: true

# Disable security features
# https://www.elastic.co/docs/reference/elasticsearch/configuration-reference/security-settings#general-security-settings
xpack.security.enabled: false
xpack.security.autoconfiguration.enabled: false
xpack.security.enrollment.enabled: false
